//! Write world-space 3D Gaussians as an INRIA-gaussian-splatting-compatible
//! binary-little-endian `.ply`. Matches `src/ply_export.cpp::write_gaussian_ply`.
//!
//! Vertex layout (per Gaussian):
//! ```text
//! x y z                  float   means (world space)
//! f_dc_0 f_dc_1 f_dc_2   float   SH DC term (harmonics[color, 0])
//! opacity                float   logit (inverse sigmoid) of `opacities[i]`
//! scale_0 scale_1 scale_2 float  log of `scales[i,d]`
//! rot_0 rot_1 rot_2 rot_3 float  quaternion wxyz (already wxyz)
//! ```
//! All 14 fields are little-endian `f32`. Viewers (e.g. the INRIA web viewer,
//! `npgertner/gaussian-splatting`) reconstruct the splat by `sigmoid(opacity)`,
//! `exp(scale)`, normalize the quaternion, and forward-evaluate SH from `f_dc_*`.

use crate::gs_adapter::Gaussians;
use crate::Result;
use std::fs::File;
use std::io::{BufWriter, Write};

/// Header for the binary `.ply`. Each line ends with `\n`; the body is raw
/// little-endian `f32` data appended immediately after `end_header\n`.
fn write_header<W: Write>(w: &mut W, n: usize) -> std::io::Result<()> {
    writeln!(w, "ply")?;
    writeln!(w, "format binary_little_endian 1.0")?;
    writeln!(w, "comment generated by depth-anything.rs (DA3 gaussians)")?;
    writeln!(w, "element vertex {n}")?;
    writeln!(w, "property float x")?;
    writeln!(w, "property float y")?;
    writeln!(w, "property float z")?;
    writeln!(w, "property float f_dc_0")?;
    writeln!(w, "property float f_dc_1")?;
    writeln!(w, "property float f_dc_2")?;
    writeln!(w, "property float opacity")?;
    writeln!(w, "property float scale_0")?;
    writeln!(w, "property float scale_1")?;
    writeln!(w, "property float scale_2")?;
    writeln!(w, "property float rot_0")?;
    writeln!(w, "property float rot_1")?;
    writeln!(w, "property float rot_2")?;
    writeln!(w, "property float rot_3")?;
    writeln!(w, "end_header")?;
    Ok(())
}

/// Write `g` to `path` as a 3DGS binary `.ply`. Returns `Err` on I/O failure or
/// if `g`'s parallel arrays have inconsistent lengths (same checks as the C++).
///
/// Matches `write_gaussian_ply` in `src/ply_export.cpp` bit-for-bit on the
/// scalar transformations (opacity clamped to `[1e-6, 1-1e-6]` then logit;
/// scales clamped to `>= 1e-9` then `log`).
pub fn write_gaussian_ply(path: &str, g: &Gaussians) -> Result<()> {
    let n = g.n;
    if n == 0 {
        return Err(crate::Error::Model("write_gaussian_ply: N == 0".into()));
    }
    if g.means.len() != n * 3
        || g.scales.len() != n * 3
        || g.rotations.len() != n * 4
        || g.opacities.len() != n
        || g.harmonics.len() != n * 3 * 9
    {
        return Err(crate::Error::Model(format!(
            "write_gaussian_ply: inconsistent Gaussian arrays (N={n})"
        )));
    }

    let f = File::create(path)?;
    let mut w = BufWriter::new(f);
    write_header(&mut w, n).map_err(io_err)?;

    let mut rec = [0u8; 14 * 4];
    for i in 0..n {
        // means
        write_f32(&mut rec[0..4], g.means[i * 3]);
        write_f32(&mut rec[4..8], g.means[i * 3 + 1]);
        write_f32(&mut rec[8..12], g.means[i * 3 + 2]);
        // f_dc = SH DC term per color channel (coeff 0 of each color).
        write_f32(&mut rec[12..16], g.harmonics[(i * 3) * 9]);
        write_f32(&mut rec[16..20], g.harmonics[(i * 3 + 1) * 9]);
        write_f32(&mut rec[20..24], g.harmonics[(i * 3 + 2) * 9]);
        // opacity as logit. Clamp into the open interval (1e-6, 1-1e-6).
        let op = g.opacities[i].clamp(1e-6, 1.0 - 1e-6);
        write_f32(&mut rec[24..28], (op / (1.0 - op)).ln());
        // scales stored as log (clamped to >= 1e-9 to avoid log(0)).
        write_f32(&mut rec[28..32], g.scales[i * 3].max(1e-9).ln());
        write_f32(&mut rec[32..36], g.scales[i * 3 + 1].max(1e-9).ln());
        write_f32(&mut rec[36..40], g.scales[i * 3 + 2].max(1e-9).ln());
        // rotation wxyz (already wxyz).
        write_f32(&mut rec[40..44], g.rotations[i * 4]);
        write_f32(&mut rec[44..48], g.rotations[i * 4 + 1]);
        write_f32(&mut rec[48..52], g.rotations[i * 4 + 2]);
        write_f32(&mut rec[52..56], g.rotations[i * 4 + 3]);
        w.write_all(&rec).map_err(io_err)?;
    }
    w.flush().map_err(io_err)?;
    Ok(())
}

fn write_f32(buf: &mut [u8], v: f32) {
    buf.copy_from_slice(&v.to_le_bytes());
}

fn io_err(e: std::io::Error) -> crate::Error {
    crate::Error::Io(e)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn one_gaussian() -> Gaussians {
        // 1 Gaussian; pick values that exercise the clamping + transforms.
        Gaussians {
            n: 1,
            means: vec![1.0, 2.0, 3.0],
            scales: vec![0.5, 1.0, 2.0], // log -> -0.693, 0.0, 0.693
            rotations: vec![1.0, 0.0, 0.0, 0.0], // identity wxyz
            // 27 entries; the DC term for color c is harmonics[c*9 + 0].
            harmonics: vec![
                0.10, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, // r: dc=0.10
                0.20, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, // g: dc=0.20
                0.30, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
            ], // b: dc=0.30
            opacities: vec![0.5], // logit(0.5) = 0
        }
    }

    fn tmp_path(name: &str) -> String {
        // target/<name> — never clutters the source tree.
        let mut p = std::env::temp_dir();
        p.push(name);
        p.to_string_lossy().into_owned()
    }

    #[test]
    fn write_header_format() {
        let mut buf: Vec<u8> = Vec::new();
        write_header(&mut buf, 7).unwrap();
        let s = String::from_utf8(buf).unwrap();
        assert!(s.starts_with("ply\n"));
        assert!(s.contains("format binary_little_endian 1.0\n"));
        assert!(s.contains("element vertex 7\n"));
        // Each property line must be present in order.
        assert!(s.contains("property float x\nproperty float y\nproperty float z\n"));
        assert!(s.contains("property float f_dc_0\nproperty float f_dc_1\nproperty float f_dc_2\n"));
        assert!(s.contains("property float opacity\n"));
        assert!(
            s.contains("property float scale_0\nproperty float scale_1\nproperty float scale_2\n")
        );
        assert!(s.contains("property float rot_0\nproperty float rot_1\nproperty float rot_2\nproperty float rot_3\n"));
        assert!(s.ends_with("end_header\n"));
    }

    #[test]
    fn rejects_zero_n() {
        let g = Gaussians::default();
        let p = tmp_path("rs_ply_zero.ply");
        let err = write_gaussian_ply(&p, &g).unwrap_err();
        assert!(matches!(err, crate::Error::Model(_)));
    }

    #[test]
    fn rejects_bad_lengths() {
        let mut g = one_gaussian();
        g.means.clear(); // wrong length
        let p = tmp_path("rs_ply_badlen.ply");
        let err = write_gaussian_ply(&p, &g).unwrap_err();
        assert!(matches!(err, crate::Error::Model(_)));
    }

    #[test]
    fn writes_one_record_bit_exact() {
        let g = one_gaussian();
        let p = tmp_path("rs_ply_one.ply");
        write_gaussian_ply(&p, &g).unwrap();

        let bytes = std::fs::read(&p).unwrap();
        let header_end = find_header_end(&bytes);
        let body = &bytes[header_end..];
        assert_eq!(body.len(), 14 * 4, "one record = 14 f32 = 56 bytes");

        let f = |i: usize| f32::from_le_bytes(body[i * 4..i * 4 + 4].try_into().unwrap());
        // means
        assert_eq!(f(0), 1.0);
        assert_eq!(f(1), 2.0);
        assert_eq!(f(2), 3.0);
        // f_dc_0..2
        assert!((f(3) - 0.10).abs() < 1e-6);
        assert!((f(4) - 0.20).abs() < 1e-6);
        assert!((f(5) - 0.30).abs() < 1e-6);
        // opacity logit(0.5) = 0
        assert!(f(6).abs() < 1e-6);
        // scales log(0.5), log(1.0), log(2.0)
        assert!((f(7) - (0.5f32).ln()).abs() < 1e-6);
        assert!((f(8) - 0.0).abs() < 1e-6);
        assert!((f(9) - (2.0f32).ln()).abs() < 1e-6);
        // rotation wxyz = (1, 0, 0, 0)
        assert!((f(10) - 1.0).abs() < 1e-6);
        assert!((f(11) - 0.0).abs() < 1e-6);
        assert!((f(12) - 0.0).abs() < 1e-6);
        assert!((f(13) - 0.0).abs() < 1e-6);
    }

    #[test]
    fn opacity_is_clamped_before_logit() {
        let mut g = one_gaussian();
        g.opacities[0] = 0.0; // would be logit(0) = -inf; clamp to 1e-6 first
        let p = tmp_path("rs_ply_oplo.ply");
        write_gaussian_ply(&p, &g).unwrap();
        let bytes = std::fs::read(&p).unwrap();
        let body = &bytes[find_header_end(&bytes)..];
        let v = f32::from_le_bytes(body[24..28].try_into().unwrap());
        // Reproduce the implementation's f32 arithmetic exactly: clamp first, then
        // logit. (Doing this in f64 in the test would diverge from the f32 op.)
        let op: f32 = 0.0f32.clamp(1e-6, 1.0 - 1e-6);
        let want = (op / (1.0 - op)).ln();
        assert!((v - want).abs() < 1e-3, "got {v}, want {want}");

        g.opacities[0] = 1.0; // would be logit(1) = +inf; clamp to 1-1e-6
        write_gaussian_ply(&p, &g).unwrap();
        let bytes = std::fs::read(&p).unwrap();
        let body = &bytes[find_header_end(&bytes)..];
        let v = f32::from_le_bytes(body[24..28].try_into().unwrap());
        let op: f32 = 1.0f32.clamp(1e-6, 1.0 - 1e-6);
        let want = (op / (1.0 - op)).ln();
        assert!((v - want).abs() < 1e-3, "got {v}, want {want}");
    }

    #[test]
    fn scale_is_clamped_before_log() {
        let mut g = one_gaussian();
        g.scales[0] = 0.0; // log(0) = -inf; clamp to 1e-9 first
        let p = tmp_path("rs_ply_sc0.ply");
        write_gaussian_ply(&p, &g).unwrap();
        let bytes = std::fs::read(&p).unwrap();
        let body = &bytes[find_header_end(&bytes)..];
        let v = f32::from_le_bytes(body[28..32].try_into().unwrap());
        let want = (1e-9f32).ln();
        assert!((v - want).abs() < 1e-3, "got {v}, want {want}");
    }

    #[test]
    fn writes_many_records() {
        // 3 Gaussians; check N=3 in the header and 3*56 bytes of body.
        let g = Gaussians {
            n: 3,
            means: vec![0.0; 9],
            scales: vec![1.0; 9],
            rotations: vec![1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
            harmonics: vec![0.0; 3 * 3 * 9],
            opacities: vec![0.5; 3],
        };
        let p = tmp_path("rs_ply_three.ply");
        write_gaussian_ply(&p, &g).unwrap();
        let bytes = std::fs::read(&p).unwrap();
        assert!(String::from_utf8_lossy(&bytes).contains("element vertex 3\n"));
        let body = &bytes[find_header_end(&bytes)..];
        assert_eq!(body.len(), 3 * 14 * 4);
    }

    fn find_header_end(bytes: &[u8]) -> usize {
        // Header ends at the byte following the `\n` of `end_header\n`.
        let marker = b"end_header\n";
        let i = bytes
            .windows(marker.len())
            .position(|w| w == marker)
            .expect("end_header marker present");
        i + marker.len()
    }
}
